### ISSUE TITLE
Vamp 095 does not deploy correctly with SQL persistence on DC/OS 1.10.0

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1036]
while Vamp 095 deploys correctly on DCOS 1.9.x it seems on DC/OS Vamp (lifter) has issues getting a consistent connection to the SQL persistence database. Sometimes it works, sometimes it doesn't, sometimes the db is created, sometimes not, sometimes records are written, sometimes not, etc.

```
[0;39m[36m20:45:25.256[0;39m [34m| INFO  | io.vamp.http_api.HttpApiBootstrap        |                                          | Binding API: 0.0.0.0:8080
[0;39m[36m20:45:28.659[0;39m [1;31m| ERROR | akka.actor.OneForOneStrategy             | amp/user/vamp/my-sql-persistence-actor-0 | Unknown database 'vamp-vamp'
[0;39mjava.sql.SQLSyntaxErrorException: Unknown database 'vamp-vamp'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.vamp.persistence.SqlPersistenceActor.read(SqlPersistenceActor.scala:29)
	at io.vamp.persistence.SqlPersistenceActor.read$(SqlPersistenceActor.scala:28)
	at io.vamp.persistence.MySqlPersistenceActor.read(MySqlPersistenceActor.scala:12)
	at io.vamp.persistence.CQRSActor$$anonfun$receive$1.applyOrElse(CQRSActor.scala:47)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:496)
	at akka.actor.Actor.aroundReceive$(Actor.scala:494)
	at io.vamp.persistence.MySqlPersistenceActor.akka$actor$DiagnosticActorLogging$$super$aroundReceive(MySqlPersistenceActor.scala:12)
	at akka.actor.DiagnosticActorLogging.aroundReceive(Actor.scala:329)
	at akka.actor.DiagnosticActorLogging.aroundReceive$(Actor.scala:327)
	at io.vamp.persistence.MySqlPersistenceActor.aroundReceive(MySqlPersistenceActor.scala:12)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jason-magnetic-io** [comment]
As the lifter application that is part of 0.9.5 is being replaced with a standalone application in 0.9.6, we will wait until the new lifer application is available before investigating this bug.

**Comment by olafmol** [comment]
There is now a Vamp DCOS docker version 0.9.5.6 that works much more stable. Let's see if we can get this into a 0.9.6 package.

**Comment by olafmol** [comment]
fixed in Vamp EE
