### ISSUE TITLE
Vamp 095 throws error when using postgres for SQL db

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1037]
using postgres universe package on DCOS 1.10:

```
[0;39m[36m07:21:31.662[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Error occurred in Persistence Initialization: 'Unable to get connection to the database: No suitable driver found for jdbc:postgresql://postgresql.marathon.l4lb.thisdcos.directory:5432?useSSL=false'.
[0;39m[36m07:21:34.557[0;39m [1;31m| ERROR | akka.actor.OneForOneStrategy             | p/user/vamp/postgres-persistence-actor-2 | FATAL: database "vamp-vamp" does not exist
[0;39morg.postgresql.util.PSQLException: FATAL: database "vamp-vamp" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:691)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:146)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc42.AbstractJdbc42Connection.<init>(AbstractJdbc42Connection.java:21)
	at org.postgresql.jdbc42.Jdbc42Connection.<init>(Jdbc42Connection.java:28)
	at org.postgresql.Driver.makeConnection(Driver.java:415)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.vamp.persistence.SqlPersistenceActor.read(SqlPersistenceActor.scala:29)
	at io.vamp.persistence.SqlPersistenceActor.read$(SqlPersistenceActor.scala:28)
	at io.vamp.persistence.PostgresPersistenceActor.read(PostgresPersistenceActor.scala:18)
	at io.vamp.persistence.CQRSActor$$anonfun$receive$1.applyOrElse(CQRSActor.scala:47)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:496)
	at akka.actor.Actor.aroundReceive$(Actor.scala:494)
	at io.vamp.persistence.PostgresPersistenceActor.akka$actor$DiagnosticActorLogging$$super$aroundReceive(PostgresPersistenceActor.scala:18)
	at akka.actor.DiagnosticActorLogging.aroundReceive(Actor.scala:329)
	at akka.actor.DiagnosticActorLogging.aroundReceive$(Actor.scala:327)
	at io.vamp.persistence.PostgresPersistenceActor.aroundReceive(PostgresPersistenceActor.scala:18)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by olafmol** [comment]
todo: check class path if postgress jdbc lib is actually included into the docker image
