### ISSUE TITLE
Vamp 095 throws timeout errors about SQL persistence actor when restarting container in DC/OS 1.10

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1046]
when restarting Vamp container it often shows this SQL persistence error (might have something to do with a SQL db filling up with records?)

```
[36m06:29:01.268[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Ask timed out on [Actor[akka://vamp/user/vamp/my-sql-persistence-actor-44#-1215381680]] after [10000 ms]. Sender[Actor[akka://vamp/user/vamp/my-sql-persistence-actor-44#-1215381680]] sent message of type "io.vamp.persistence.CommonPersistenceMessages$Delete".
[0;39makka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://vamp/user/vamp/my-sql-persistence-actor-44#-1215381680]] after [10000 ms]. Sender[Actor[akka://vamp/user/vamp/my-sql-persistence-actor-44#-1215381680]] sent message of type "io.vamp.persistence.CommonPersistenceMessages$Delete".
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:864)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:109)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:103)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:862)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jason-magnetic-io** [comment]
Thanks @olafmol, is this a random event or is it consistently reproducible? Which version of vamp are you using and which db?

**Comment by olafmol** [comment]
It seems to happen on DC/OS 1.10.0 with Vamp 095-DCOS, and happens when there is already some deployments running.

**Comment by olafmol** [comment]
Fixed in Vamp EE
