### ISSUE TITLE
Events are not retrieved for specific tags

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#150]
Event:

```json
{
  "tags": [
    "services",
    "routes:159f475e-3673-4ced-b852-e1f95ce840dc_sava_80",
    "routes",
    "metrics:qcur",
    "servers:6fd83b1fd01f7dd9eb7f",
    "services:sava:1",
    "servers",
    "metrics"
  ],
  "value": 0,
  "timestamp": "2015-06-04T15:12:38.001Z",
  "type": "router-metric"
}
```

Query works fine:

```json
{
    "tags": ["routes"]
}
```

but not this one:

```json
{
    "tags": ["routes:159f475e-3673-4ced-b852-e1f95ce840dc_sava_80"]
}
```

**Comment by tnolet** [comment]
In the docker container setup I can see the following error in the logs:

```
15:22:24.442 | ERROR | io.vamp.pulse.http.HttpServerActor       | kka://vamp-pulse/user/http-server-actor$ | Request to http://localhost:8083/api/v1/events could not be handled normally: com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
java.lang.RuntimeException: com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
	at io.vamp.common.http.RestApiMarshaller$class.toJson(RestApiBase.scala:71) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at io.vamp.pulse.http.HttpServerActor.toJson(HttpServerActor.scala:19) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at io.vamp.common.http.RestApiMarshaller$$anonfun$jsonMarshaller$1.apply(RestApiBase.scala:55) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at io.vamp.common.http.RestApiMarshaller$$anonfun$jsonMarshaller$1.apply(RestApiBase.scala:54) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.Marshaller$$anon$2.apply(Marshaller.scala:47) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.BasicToResponseMarshallers$$anon$1.apply(BasicToResponseMarshallers.scala:35) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.BasicToResponseMarshallers$$anon$1.apply(BasicToResponseMarshallers.scala:22) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anonfun$compose$1.apply(Marshaller.scala:69) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anonfun$compose$1.apply(Marshaller.scala:69) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anon$3.apply(Marshaller.scala:81) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anonfun$oneOf$1.spray$httpx$marshalling$ToResponseMarshaller$$anonfun$$tryNext$1(Marshaller.scala:104) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anonfun$oneOf$1.apply(Marshaller.scala:114) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anonfun$oneOf$1.apply(Marshaller.scala:101) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshaller$$anon$4.apply(Marshaller.scala:92) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshallable$$anon$6.marshal(Marshaller.scala:141) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshallable$$anon$7.apply(Marshaller.scala:145) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.httpx.marshalling.ToResponseMarshallable$$anon$7.apply(Marshaller.scala:144) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.RequestContext.complete(RequestContext.scala:237) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:49) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:48) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:81) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:79) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [pulse-assembly-0.7.6.jar:0.7.6.67b66e6]
Caused by: com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '': path has a leading, trailing, or two adjacent pe
```

**Comment by tnolet** [comment]
From elasticsearch, this doesn't work when you provide the search key in the query field:

```
POST http://192.168.59.103:9200/vamp/_search
{
  "query" : {
    "term": { "tags": "routes:a159f475e-3673-4ced-b852-e1f95ce840dc_sava_80" }   
  }    
}
```

However, you do get

**Comment by dragoslav** [comment]
Using "not_analyzed" for tags and type.
