### ISSUE TITLE
Vamp CLI should give "nice" messages if Java 8 is not installed and VAMP_HOST is not present

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#169]
From an end user perspective, Vamp-CLI should give a nice message if the user is not at the right JDK level. This now happens:
```
root@custom-6212-6e5:~# vamp
Exception in thread "main" java.lang.UnsupportedClassVersionError: Boot : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:787)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:447)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:476
```

We would want something like:

```
root@custom-6212-6e5:~# vamp

Hi, you are currently not using Java JDK8. We need that for running Vamp.
Please check http://vamp.io/installation for details
```

Similarly, we want to check on every run if the VAMP_HOST variable is set, instead of:

```
root@custom-6212-6e5:~# vamp breeds
ERROR: Parameter 'host missing
```

we would want something like:

```
root@custom-6212-6e5:~# vamp breeds
Hi, we can't find the VAMP_HOST environment variable. Please set it with the correct Vamp host.
Please check http://vamp.io/installation for details
```

**Comment by plamola** [comment]
Added `check_java.sh` to be included in the startup script. 

If the java version is < 1.8, it says:

```bash
Hi, you seem to have Java version 1.7.0_67 installed. I need Java version 1.8 or higher.
Please check http://vamp.io/installation for details
```

If no java version can be found, it will display:

```bash
Hi, it appears I cannot find your Java installation. I really need Java 1.8+ to be installed.
Please check http://vamp.io/installation for details
```

**Comment by tnolet** [comment]
awesome :+1:  :

**Comment by plamola** [comment]
For the missing `VAMP_HOST` or `--host` command line argument, I've added the following message:

```bash
Sorry, I don't know to which Vamp host I should talk.

Setup a host in the VAMP_HOST environment variable, or use the --host command line argument.
Please check http://vamp.io/installation for further details
```
