### ISSUE TITLE
Weird serialization behaviour with CLI: "special characters are not allowed" / "unknown token"

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#237]
When getting info, i.e.  `vamp info`, the screen is taken over with all kinds of special characters"

```
java -jar vamp-cli-0.7.7.400410b.jar info
�WK��6��W�''@e�EI֥mzI[)�m�
��h��$*|x�����m��=�
                   s8���=�Rt�J���~Xv�#톯�[�d�$�7�#����D�i�ŧcW.�T�~G�Ii���Y�h��@�9���kVk#���H�����(\�_⹏���j�����D�*t�^i��y�q�9iz��cE��<�l�}��
���R�ZQ��c�Rڒ�؞Ǐ�\�?
1^�8��؛����ق�4��    B�zx��i��k�IP�>������F����n�^�AXW����
��j�g���c��pfA�AQRƸ��U�s���(�,��"���Ԭ�R��#�=�Uc�7az�(�n$a�Fi�3I���H-"���6�K�D2����D�65�O����B���/Y3݁�tȥ�v��O��SS�p0����}\��G(���M��j4��b���6~��+��,C��0��0
�_�����MK�R�d��~���/��Y!_A
                          W�*_�4�ft�i9'��e'�����^�N>��l {�j�[�4�d��M��Ԑ�
                                                                        �V�Ÿ<s�N�6@�2����P��a�R�We��r�o�R�ӆ�i.�IG=SvG?d� -g5(��˅UP��`�[q7:�rX��-�*1>j�Um�t�PW'��fe&�%��y�%��,�Wً�f�@����"WSu�|�Ɵ����p"
                  L_�7f^H��
                           j�4�
���|�UG$�
         �q������ ��^H�L���
                           �>��M;�pg�z���(�p�θn�Q�a']u1�{a+�<��B�z���</�g-����S��U_j��J�8��mz��f�L�[k�ҼV̶�r
                                                                                                          ���AV�߅A?���k���e��Z�V�Su&��<�v0T8��%�8 |t<���8iMͮGhj�i�T��۞j/��-wֿ�����uah՛��iT&���{O�)K�4��:eiR8�ia�mh����E��z�NC�vW�`;�x߰'oQ����67�,�xV��)�5�ݎF�6#[7�Lh�N��;*9;˃1%��y|fq�eW�
M_�NH��0��4n��

,G:�&^^d߱�V��o���㿋��gn�1-y���^���!�*:��P��4y�z@��UܙeZ��#�/�r���m#Q�?�B�l}
�����@�`B�;a���wA2]^)hXv��z�D�                                           dO�6vӝ�@ik��+�"�������=�XEQ'�c��
��z�V�w���������=L�H�9�ǔ@+|�R�%K�tJ�o�+ޯ�V�e	m���6
```

When creating a breed with the CLI, you get the following error. There are no special character in the breed:

```yaml
name: rabo-test-app-2
deployable: cmd://dropwizardtest*/start.sh
ports:
  http: 9080/tcp
environment_variables:
  DW_LOGLEVEL: info
  DW_JDBC_URL: jdbc:mysql://lsrv4180.linux.rabobank.nl/dropwizardtest
```

Tims-MacBook-Pro:scala-2.11 tim$ java -jar vamp-cli-0.7.7.a5bbd9f.jar create breed --file br_template.yaml 
15:01:58.903 [main] ERROR i.v.common.notification.Notification - Error: special characters are not allowed
Exception in thread "main" io.vamp.common.notification.NotificationErrorException: Error: special characters are not allowed
	at io.vamp.common.notification.LoggingNotificationProvider$class.exception(NotificationProvider.scala:38)
	at io.vamp.core.model.reader.BreedReader$.exception(BreedReader.scala:9)
	at io.vamp.common.notification.NotificationProvider$class.error(NotificationProvider.scala:14)
	at io.vamp.core.model.reader.BreedReader$.error(BreedReader.scala:9)
	at io.vamp.core.model.reader.YamlReader$class.load(Reader.scala:62)
	at io.vamp.core.model.reader.BreedReader$.load(BreedReader.scala:9)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:53)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:49)
	at io.vamp.core.model.reader.BreedReader$.read(BreedReader.scala:9)
	at io.vamp.core.cli.backend.VampHostCalls$.createBreed(VampHostCalls.scala:46)
	at io.vamp.core.cli.commands.PerformCommand$.doCreateCommand(PerformCommand.scala:196)
	at io.vamp.core.cli.commands.PerformCommand$.doCommand(PerformCommand.scala:32)
	at io.vamp.core.cli.VampCli$class.main(VampCli.scala:17)
	at io.vamp.core.cli.Boot$.main(Boot.scala:3)
	at io.vamp.core.cli.Boot.main(Boot.scala)

**Comment by dragoslav** [comment]
gzip response and http client library we use doesn't handle it by default
