### ISSUE TITLE
Vamp Pulse does not connect to SSE stream: io.vamp.pulse.eventstream.SSEConnectionActor

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#240]
On starting straight from the source. Vamp Router is running on http://localhost:10001

```
17:09:11.017 [vamp-pulse-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
17:09:11.903 [vamp-pulse-akka.actor.default-dispatcher-4] ERROR akka.actor.OneForOneStrategy - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at akka.util.Reflect$.instantiate(Reflect.scala:66) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.11.jar:na]
	... 9 common frames omitted
Caused by: java.lang.IllegalArgumentException: no matching constructor found on class io.vamp.pulse.eventstream.SSEConnectionActor for arguments [class scala.collection.immutable.$colon$colon]
	at akka.util.Reflect$.error$1(Reflect.scala:82) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.util.Reflect$.findConstructor(Reflect.scala:106) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ArgsReflectConstructor.<init>(Props.scala:350) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.IndirectActorProducer$.apply(Props.scala:309) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.producer(Props.scala:176) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.<init>(Props.scala:189) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props$.apply(Props.scala:93) ~[akka-actor_2.11-2.3.11.jar:na]
	at io.vamp.pulse.eventstream.SSEConnectionActor$.props(SSEConnectionActor.scala:28) ~[classes/:na]
	at io.vamp.common.akka.ActorSupport$.actorOf(ActorSupport.scala:24) ~[common_2.11-0.7.7.05f2aa4.jar:0.7.7.05f2aa4]
	at io.vamp.common.akka.ActorSupport$class.actorOf(ActorSupport.scala:37) ~[common_2.11-0.7.7.05f2aa4.jar:0.7.7.05f2aa4]
	at io.vamp.pulse.eventstream.SSESupervisionActor.actorOf(SSESupervisionActor.scala:14) ~[classes/:na]
	at io.vamp.pulse.eventstream.SSESupervisionActor.<init>(SSESupervisionActor.scala:16) ~[classes/:na]
	... 18 common frames omitted
```

**Comment by dragoslav** [comment]
due to change/refactoring in vamp common
