### ISSUE TITLE
Stack trace in vamp-pulse log when vamp-router is unreachable

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#266]
When vamp-router is not reachable, a stack trace is logged:
```log
07:43:14.869 | ERROR | i.v.pulse.eventstream.SSEConnectionActor | esupervision-actor$/sseconnection-actor$ | Unable to connect: stream http://localhost:10001/v1/stats/stream is unreachable.
07:43:14.873 | ERROR | akka.actor.OneForOneStrategy             | pervision-actor$/sseconnection-actor$/$a | Expected authority at index 12: localhost://
java.net.URISyntaxException: Expected authority at index 12: localhost://
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_45]
	at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_45]
	at java.net.URI$Parser.parseHierarchical(URI.java:3102) ~[na:1.8.0_45]
	at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_45]
	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_45]
	at dispatch.RawUri.toUri(uri.scala:13) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.RawUri.toString(uri.scala:24) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.url$$anonfun$apply$3.apply(requests.scala:58) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.url$$anonfun$apply$3.apply(requests.scala:58) ~[vamp-pulse.jar:0.7.8.10]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[vamp-pulse.jar:0.7.8.10]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[vamp-pulse.jar:0.7.8.10]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[vamp-pulse.jar:0.7.8.10]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.Req.toRequestBuilder(requests.scala:19) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.Req.toRequest(requests.scala:27) ~[vamp-pulse.jar:0.7.8.10]
	at dispatch.RequestHandlerTupleBuilder.OK(handlers.scala:15) ~[vamp-pulse.jar:0.7.8.10]
	at io.vamp.common.http.RestClient$.http(RestClient.scala:69) ~[vamp-pulse.jar:0.7.8.10]
	at io.vamp.common.http.RestClient$.post(RestClient.scala:32) ~[vamp-pulse.jar:0.7.8.10]
	at io.vamp.pulse.client.PulseClient.sendEvent(PulseClient.scala:20) ~[vamp-pulse.jar:0.7.8.10]
	at io.vamp.pulse.notification.AbstractPulseNotificationActor.error(AbstractPulseNotificationActor.scala:12) ~[vamp-pulse.jar:0.7.8.10]
	at io.vamp.common.notification.NotificationActor$$anonfun$receive$1.applyOrElse(NotificationActor.scala:16) ~[vamp-pulse.jar:0.7.8.10]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[vamp-pulse.jar:0.7.8.10]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:47) ~[vamp-pulse.jar:0.7.8.10]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [vamp-pulse.jar:0.7.8.10]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [vamp-pulse.jar:0.7.8.10]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [vamp-pulse.jar:0.7.8.10]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [vamp-pulse.jar:0.7.8.10]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [vamp-pulse.jar:0.7.8.10]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp-pulse.jar:0.7.8.10]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp-pulse.jar:0.7.8.10]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp-pulse.jar:0.7.8.10]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp-pulse.jar:0.7.8.10]
```

Catch this error and replace it with a less verbose error message.

**Comment by plamola** [comment]
Getting two stack traces when router is down in the vamp-core log:
```
16:18:50.239 | DEBUG | i.v.c.router_driver.DefaultRouterDriver  |                                          | router get all
16:18:50.250 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
16:18:50.252 | ERROR | io.vamp.common.notification.Notification |                                          | java.net.ConnectException: Connection refused: /192.168.59.103:10001 to http://192.168.59.103:10001/v1/routes
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: /192.168.59.103:10001 to http://192.168.59.103:10001/v1/routes
	at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342) ~[async-http-client-1.8.10.jar:na]
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:107) ~[async-http-client-1.8.10.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.9.6.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
Caused by: java.net.ConnectException: Connection refused: /192.168.59.103:10001 to http://192.168.59.103:10001/v1/routes
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103) ~[async-http-client-1.8.10.jar:na]
	... 12 common frames omitted
Caused by: java.net.ConnectException: Connection refused: /192.168.59.103:10001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_31]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[na:1.8.0_31]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.9.6.Final.jar:na]
	... 8 common frames omitted
16:18:50.253 | ERROR | akka.actor.OneForOneStrategy             | e/user/deployment-synchronization-actor$ | io.vamp.common.notification.NotificationErrorException cannot be cast to io.vamp.core.router_driver.DeploymentRoutes
java.lang.ClassCastException: io.vamp.common.notification.NotificationErrorException cannot be cast to io.vamp.core.router_driver.DeploymentRoutes
	at io.vamp.core.operation.deployment.DeploymentSynchronizationActor.io$vamp$core$operation$deployment$DeploymentSynchronizationActor$$synchronize(DeploymentSynchronizationActor.scala:84) ~[classes/:na]
	at io.vamp.core.operation.deployment.DeploymentSynchronizationActor$$anonfun$receive$1.applyOrElse(DeploymentSynchronizationActor.scala:72) ~[classes/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.11.jar:na]
	at io.vamp.core.operation.deployment.DeploymentSynchronizationActor.aroundReceive(DeploymentSynchronizationActor.scala:43) ~[classes/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
```

**Comment by plamola** [comment]
Caught the Core errors and wrote something less verbose:
```
12:49:21.666 | DEBUG | i.v.c.router_driver.DefaultRouterDriver  |                                          | router get all
12:49:21.668 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
12:49:21.668 | ERROR | io.vamp.common.notification.Notification |                                          | java.net.ConnectException: Connection refused: /192.168.59.103:10001 to http://192.168.59.103:10001/v1/routes
12:49:21.669 | ERROR | i.v.c.o.d.DeploymentSynchronizationActor | e/user/deployment-synchronization-actor$ | Synchronisation not possible 
```

**Comment by dragoslav** [comment]
One-line error log message (e.g. connection refused); stack trace only for TRACE log level.
