### ISSUE TITLE
Docker 1.8 compatibility

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#342]
At this moment there seems to be an issue with Docker 1.8 using the Docker driver. Deploying seems to hang. We should investigate.

**Comment by JoshFalken** [comment]
@tnolet I was also encountering some problems after upgrade with deployment (stayed in the readyfordeployment-phase) What did the trick for me was uninstalling VAMP, removing the data-folders of VAMP (/usr/share/vamp-[core|pulse|router]/data) and reinstalling VAMP. I'm running Docker version 1.8.1, build d12ea79. Could of course also be that I was having a whole other problem.

**Comment by jgordijn** [comment]
Currently running with latest docker and docker toolbox on my mac. And I can deploy dockers via the UI.

Running find for me with following command:
```
docker run --net=host -v ~/.docker/machine/machines/default:/certs -e "DOCKER_TLS_VERIFY=1" -e "DOCKER_HOST=`docker-machine url default`" -e "DOCKER_CERT_PATH=/certs" magneticio/vamp-docker:0.7.10
```

```
$ docker -v
Docker version 1.8.2, build 0a8c2e3
```

**Comment by olafmol** [comment]
Two related issues: 

https://github.com/magneticio/vamp/issues/385
https://github.com/magneticio/vamp/issues/384

I'm running Boot2Docker version 1.8.2, docker-machine version 0.4.1 (coming with the new Docker Toolbox)

**Comment by olafmol** [comment]
This issue might also be related: https://github.com/magneticio/vamp-router/issues/24

**Comment by olafmol** [comment]
I think that if we can make Vamp-docker:latest run without glitches from within Kitematic (https://kitematic.com) which comes with the new Docker Toolbox, we have a very robust Docker-quickstart going on. Would be awesome for "n00b-adoption" to get a feeling for Vamp.

**Comment by olafmol** [comment]
After installing the Docker Toolbox, and starting Docker by running the "Docker QuickStart Terminal.app" and then pasting @jgordijn 's command, i get Vamp running and the GUI in my browser. When deploying the first step of the tutorial (http://vamp.io/documentation/guides/getting-started-tutorial/1-deploying/) the deployment stays in "ready for deployment" (yellow) forever, and never reaches green "deployed".

In my logs these errors show up:

19:26:04.194 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
19:26:04.194 | ERROR | io.vamp.common.notification.Notification |                                          | None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347) ~[vamp-core.jar:0.7.10]
	at scala.None$.get(Option.scala:345) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver.io$vamp$core$router_driver$DefaultRouterDriver$$server(DefaultRouterDriver.scala:101) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver$$anonfun$services$1$$anonfun$apply$5.apply(DefaultRouterDriver.scala:89) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver$$anonfun$services$1$$anonfun$apply$5.apply(DefaultRouterDriver.scala:89) ~[vamp-core.jar:0.7.10]
	at scala.collection.immutable.List.map(List.scala:273) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver$$anonfun$services$1.apply(DefaultRouterDriver.scala:89) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver$$anonfun$services$1.apply(DefaultRouterDriver.scala:89) ~[vamp-core.jar:0.7.10]
	at scala.collection.immutable.List.map(List.scala:273) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver.services(DefaultRouterDriver.scala:89) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver.route(DefaultRouterDriver.scala:69) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.DefaultRouterDriver.create(DefaultRouterDriver.scala:40) ~[vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.RouterDriverActor.reply(RouterDriverActor.scala:47) [vamp-core.jar:0.7.10]
	at io.vamp.common.akka.ReplyActor$$anonfun$receive$1.applyOrElse(ReplyActor.scala:19) [vamp-core.jar:0.7.10]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [vamp-core.jar:0.7.10]
	at io.vamp.core.router_driver.RouterDriverActor.aroundReceive(RouterDriverActor.scala:33) [vamp-core.jar:0.7.10]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [vamp-core.jar:0.7.10]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [vamp-core.jar:0.7.10]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [vamp-core.jar:0.7.10]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [vamp-core.jar:0.7.10]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [vamp-core.jar:0.7.10]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp-core.jar:0.7.10]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp-core.jar:0.7.10]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp-core.jar:0.7.10]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp-core.jar:0.7.10]
