### ISSUE TITLE
Investigate persistance exception

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#343]
gettint this when running last core build:
11:46:44.974 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@257cff32
11:46:44.974 | ERROR | io.vamp.common.notification.Notification |                                          | scala.concurrent.impl.Promise$DefaultPromise@257cff32
11:46:44.975 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: io.vamp.common.notification.NotificationErrorException: Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@257cff32
11:46:44.976 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@257cff32
io.vamp.common.notification.NotificationErrorException: Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@257cff32
at io.vamp.common.notification.LoggingNotificationProvider$class.reportException(NotificationProvider.scala:39) ~[vamp-core.jar:0.7.9-dev.7527c64]
at io.vamp.core.persistence.DecoratorPersistenceActor.reportException(DecoratorPersistenceActor.scala:12) ~[vamp-core.jar:0.7.9-dev.7527c64]
at io.vamp.common.akka.ReplyActor$class.failure(ReplyActor.scala:39) ~[vamp-core.jar:0.7.9-dev.7527c64]
at io.vamp.core.persistence.DecoratorPersistenceActor.failure(DecoratorPersistenceActor.scala:12) ~[vamp-core.jar:0.7.9-dev.7527c64]
at io.vamp.common.akka.ReplyActor$$anonfun$checked$1.apply(ReplyActor.scala:35) ~[vamp-core.jar:0.7.9-dev.7527c64]
at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[vamp-core.jar:0.7.9-dev.7527c64]
at scala.util.Try$.apply(Try.scala:192) ~[vamp-core.jar:0.7.9-dev.7527c64]
at scala.util.Success.map(Try.scala:237) ~[vamp-core.jar:0.7.9-dev.7527c64]
at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[vamp-core.jar:0.7.9-dev.7527c64]

**Comment by tnolet** [comment]
bug is still there in core 0.7.9-dev.794750f using JDBC persistence. Storing a blueprint works, but then trying to access it for editing throws:

```
12:47:50.518 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@239408e8
12:47:50.526 | ERROR | io.vamp.common.notification.Notification |                                          | scala.concurrent.impl.Promise$DefaultPromise@239408e8
12:47:50.526 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: io.vamp.common.notification.NotificationErrorException: Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@239408e8
12:47:50.527 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@239408e8
io.vamp.common.notification.NotificationErrorException: Persistence operation failure. Reason: scala.concurrent.impl.Promise$DefaultPromise@239408e8
	at io.vamp.common.notification.LoggingNotificationProvider$class.reportException(NotificationProvider.scala:39) ~[vamp-core.jar:0.7.9-dev.794750f]
	at io.vamp.core.persistence.DecoratorPersistenceActor.reportException(DecoratorPersistenceActor.scala:12) ~[vamp-core.jar:0.7.9-dev.794750f]
	at io.vamp.common.akka.ReplyActor$class.failure(ReplyActor.scala:39) ~[vamp-core.jar:0.7.9-dev.794750f]
	at io.vamp.core.persistence.DecoratorPersistenceActor.failure(DecoratorPersistenceActor.scala:12) ~[vamp-core.jar:0.7.9-dev.794750f]
	at io.vamp.common.akka.ReplyActor$$anonfun$checked$1.apply(ReplyActor.scala:35) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.util.Try$.apply(Try.scala:192) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.util.Success.map(Try.scala:237) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [vamp-core.jar:0.7.9-dev.794750f]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp-core.jar:0.7.9-dev.794750f]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java
```
