### ISSUE TITLE
Problem deploying Sava 1.2 on latest Vamp-Core develop

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#352]
During regression testing, I'm not able to get Sava 1.2 running properly, using the blueprint from the tutorial:
http://vamp.io/documentation/guides/getting-started-tutorial/3-splitting-services/

I'm using the latest Vamp Core from development, together with the 0.7.9. docker image of Vamp-Router.

Vamp reports everything deployed, but accessing the application endpoint results in a 503.
```
14:24:16.634 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_2c8fb1128ab9a09fda8f does not exist, needs creating
14:24:16.635 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_43f71c7977ba711c70f4 does not exist, needs creating
14:24:16.946 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_2c8fb1128ab9a09fda8f does not exist, needs creating
14:24:16.947 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_43f71c7977ba711c70f4 does not exist, needs creating
14:24:18.771 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router create: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_backend1_8080
14:24:18.771 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router create: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_backend2_8080
14:24:21.771 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_ae785ad2bf8eace4bbb7 does not exist, needs creating
14:24:23.756 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router create: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_sava_8080
14:24:25.794 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router create: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_9060
```

Undeploying gives a stack trace.

```
14:25:16.108 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router remove: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_sava_8080
14:25:16.109 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router remove: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_backend1_8080
14:25:16.109 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router remove: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_backend2_8080
14:25:16.119 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
14:25:16.121 | ERROR | io.vamp.common.notification.Notification |                                          | dispatch.StatusCode: Unexpected response status: 500
java.util.concurrent.ExecutionException: dispatch.StatusCode: Unexpected response status: 500
	at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:326) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1533) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1550) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2700(NettyAsyncHttpProvider.java:161) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2220) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1228) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[vamp-core.jar:0.7.9.5]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[vamp-core.jar:0.7.9.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
Caused by: dispatch.StatusCode: Unexpected response status: 500
	at io.vamp.common.http.RestClient$$anon$1.onCompleted(RestClient.scala:73) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:293) ~[vamp-core.jar:0.7.9.5]
	at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:320) ~[vamp-core.jar:0.7.9.5]
	... 31 common frames omitted
14:25:16.776 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | docker delete app: /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_ae785ad2bf8eace4bbb7
14:25:16.776 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | docker delete app: /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_2c8fb1128ab9a09fda8f
14:25:16.777 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | docker delete app: /vamp_94ccd1ea-15bd-4802-9c3a-416c1853c94b_43f71c7977ba711c70f4
14:25:17.758 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router remove: 94ccd1ea-15bd-4802-9c3a-416c1853c94b_9060
```

The routes are removed, as is the deployment.

This problem does not occur when using the Vamp-core 0.7.9 docker image.

**Comment by dragoslav** [comment]
This is related to Router and how it handles concurrent requests, additional log (TRACE level):

```
13:02:22.064 | TRACE | io.vamp.common.http.RestClient$          |                                          | req [DELETE http://10.40.170.254:10001/v1/routes/264fbe6b-fdfb-4839-8162-5546c680a500_frontend_8081]
13:02:22.186 | TRACE | io.vamp.common.http.RestClient$          |                                          | Unexpected status code: 500, for response: {"status":"Error reloading the HAproxy configuration"}

13:02:22.189 | TRACE | io.vamp.common.http.RestClient$          |                                          | rsp [DELETE http://10.40.170.254:10001/v1/routes/264fbe6b-fdfb-4839-8162-5546c680a500_frontend_8081] - 
13:02:22.190 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
13:02:22.193 | ERROR | io.vamp.common.notification.Notification |                                          | dispatch.StatusCode: Unexpected response status: 500
java.util.concurrent.ExecutionException: dispatch.StatusCode: Unexpected response status: 500
	at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:326) ~[async-http-client-1.8.10.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1533) ~[async-http-client-1.8.10.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1550) ~[async-http-client-1.8.10.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2700(NettyAsyncHttpProvider.java:161) ~[async-http-client-1.8.10.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2220) ~[async-http-client-1.8.10.jar:na]
```

**Comment by dragoslav** [comment]
I've added synchronous RouterDriverActor implementation - this is a workaround.
Once we have the solution in Router, RouterDriverActor should be reverted (check out the source code).
