### ISSUE TITLE
Vamp cli cannot list deployments

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#408]
See stacktrace below 
vamp-core: 0.7.11
vamp-cli: 0.7.11

```shell
$ vamp list deployments
NAME                                    CLUSTERS
Exception in thread "main" java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1317)
	at io.vamp.core.model.reader.DeploymentReader$.state(DeploymentReader.scala:85)
	at io.vamp.core.model.reader.DeploymentReader$.io$vamp$core$model$reader$DeploymentReader$$parseService(DeploymentReader.scala:49)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1$$anonfun$apply$1.apply(DeploymentReader.scala:24)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1$$anonfun$apply$1.apply(DeploymentReader.scala:24)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1.apply(DeploymentReader.scala:24)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1.apply(DeploymentReader.scala:17)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.LinkedHashMap.foreach(LinkedHashMap.scala:139)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at io.vamp.core.model.reader.DeploymentReader$.parse(DeploymentReader.scala:17)
	at io.vamp.core.model.reader.DeploymentReader$.parse(DeploymentReader.scala:12)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:83)
	at io.vamp.core.model.reader.DeploymentReader$.read(DeploymentReader.scala:12)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:54)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:49)
	at io.vamp.core.model.reader.DeploymentReader$.read(DeploymentReader.scala:12)
	at io.vamp.core.cli.backend.VampHostCalls$$anonfun$getDeployments$1.apply(VampHostCalls.scala:171)
	at io.vamp.core.cli.backend.VampHostCalls$$anonfun$getDeployments$1.apply(VampHostCalls.scala:171)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.vamp.core.cli.backend.VampHostCalls$.getDeployments(VampHostCalls.scala:171)
	at io.vamp.core.cli.commands.PerformCommand$.doListCommand(PerformCommand.scala:43)
	at io.vamp.core.cli.commands.PerformCommand$.doCommand(PerformCommand.scala:19)
	at io.vamp.core.cli.VampCli$class.main(VampCli.scala:33)
	at Boot$.main(Boot.scala:3)
	at Boot.main(Boot.scala)
```

**Comment by jgordijn** [comment]
It seems that every command with `deployments` gives an error:

```shell
$ vamp inspect deployment f4ee557f-5d72-4b31-a6b4-373dc6f202b2
Exception in thread "main" java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1317)
	at io.vamp.core.model.reader.DeploymentReader$.state(DeploymentReader.scala:85)
	at io.vamp.core.model.reader.DeploymentReader$.io$vamp$core$model$reader$DeploymentReader$$parseService(DeploymentReader.scala:49)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1$$anonfun$apply$1.apply(DeploymentReader.scala:24)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1$$anonfun$apply$1.apply(DeploymentReader.scala:24)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1.apply(DeploymentReader.scala:24)
	at io.vamp.core.model.reader.DeploymentReader$$anonfun$1.apply(DeploymentReader.scala:17)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.LinkedHashMap.foreach(LinkedHashMap.scala:139)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at io.vamp.core.model.reader.DeploymentReader$.parse(DeploymentReader.scala:17)
	at io.vamp.core.model.reader.DeploymentReader$.parse(DeploymentReader.scala:12)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:83)
	at io.vamp.core.model.reader.DeploymentReader$.read(DeploymentReader.scala:12)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:54)
	at io.vamp.core.model.reader.YamlReader$class.read(Reader.scala:49)
	at io.vamp.core.model.reader.DeploymentReader$.read(DeploymentReader.scala:12)
	at io.vamp.core.cli.backend.VampHostCalls$$anonfun$getDeployment$1.apply(VampHostCalls.scala:218)
	at io.vamp.core.cli.backend.VampHostCalls$$anonfun$getDeployment$1.apply(VampHostCalls.scala:218)
	at scala.Option.map(Option.scala:146)
	at io.vamp.core.cli.backend.VampHostCalls$.getDeployment(VampHostCalls.scala:218)
	at io.vamp.core.cli.commands.PerformCommand$.doInspectCommand(PerformCommand.scala:82)
	at io.vamp.core.cli.commands.PerformCommand$.doCommand(PerformCommand.scala:20)
	at io.vamp.core.cli.VampCli$class.main(VampCli.scala:33)
	at Boot$.main(Boot.scala:3)
	at Boot.main(Boot.scala)
```

**Comment by olafmol** [comment]
could you check if this behaviour is new for 0.7.11 and was not happening in 0.7.10? cheers!

**Comment by dragoslav** [comment]
This seems only in 0.7.11, I'll take a look now.

**Comment by dragoslav** [comment]
@olafmol it requires a new release 0.7.11.1 or to keep it for 0.8.0
