### ISSUE TITLE
The request content was malformed. Persistence operation failure.

### ISSUE THREAD

**Issue by zutherb** [magneticio/vamp#411]
I got the following error when i try to upload the sava example (https://raw.githubusercontent.com/magneticio/sava/master/blueprints/sava_1.0.yaml) since updating to 0.7.11.1 and my vamp example (https://github.com/zutherb/AppStash/blob/master/vamp/shop.yml) as well.

```bash
*   Trying 172.31.1.11...
* Connected to 172.31.1.11 (172.31.1.11) port 8081 (#0)
> POST /api/v1/deployments HTTP/1.1
> Host: 172.31.1.11:8081
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/x-yaml
> Content-Length: 283
> 
* upload completely sent off: 283 out of 283 bytes
< HTTP/1.1 400 Bad Request
< Date: Mon, 26 Oct 2015 14:28:55 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 79
< 
* Connection #0 to host 172.31.1.11 left intact
{"message":"The request content was malformed. Persistence operation failure."}%  
``

**Comment by dragoslav** [comment]
Hi @zutherb we have added more granular service states during deployment and that breaks old 0.7.10 SQL schema. Vamp doesn't update automatically schema and I suspect that's the problem in your case. Do you use the 0.7.11.1 Docker image or you installed all Vamp components separately?

**Comment by olafmol** [comment]
Cannot reproduce. I installed Vamp 0.7.11 using the Docker quickstart on Mac OS X and used the sava blueprint, as well as the shop blueprint. Both deployed correctly.

**Comment by olafmol** [comment]
I got another issue though when deploying Bernds shop example blueprint: after a while the following error showed up in the logs:

14:49:40.227 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_1faf6125-0160-4c3a-acb3-b6d2ff6c14e4_redis does not exist, needs creating
14:49:40.232 | ERROR | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] pulling image redis:latest failed: could not find image: no such id: c08dd1f8fad9ff2622a1b5d74650a8e494ee380b74030e21584fea05079c2818
14:49:40.233 | ERROR | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] pulling image redis:latest failed: could not find image: no such id: c08dd1f8fad9ff2622a1b5d74650a8e494ee380b74030e21584fea05079c2818

and then after some more minutes:

 14:52:31.666 api NOTI ==>  GET   /v1/routes                                         200     30.969µs 
14:52:31.973 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_1faf6125-0160-4c3a-acb3-b6d2ff6c14e4_product does not exist, needs creating
14:52:31.983 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_1faf6125-0160-4c3a-acb3-b6d2ff6c14e4_cart does not exist, needs creating
14:52:32.185 | INFO  | akka.actor.DeadLetterActorRef            | akka://vamp-core/deadLetters             | Message [scala.collection.immutable.Map$Map4] from Actor[akka://vamp-core/deadLetters] to Actor[akka://vamp-core/deadLetters] was not delivered. [84] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
14:52:32.321 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | [DEPLOY] Container /vamp_1faf6125-0160-4c3a-acb3-b6d2ff6c14e4_navigation does not exist, needs creating
14:52:32.420 api NOTI ==>  HEAD  /v1/stats/stream                                   200    201.527µs 
14:52:32.561 | ERROR | io.vamp.core.rest_api.HttpServerActor    | akka://vamp-core/user/http-server-actor  | Request to http://192.168.99.100:8080/api/v1/deployments/1faf6125-0160-4c3a-acb3-b6d2ff6c14e4 could not be handled normally: Ask timed out on [Actor[akka://vamp-core/user/jdbc-persistence-actor#2146881835]] after [10000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://vamp-core/user/jdbc-persistence-actor#2146881835]] after [10000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334) ~[vamp-core.jar:0.7.11.1]
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[vamp-core.jar:0.7.11.1]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[vamp-core.jar:0.7.11.1]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[vamp-core.jar:0.7.11.1]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[vamp-core.jar:0.7.11.1]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[vamp-core.jar:0.7.11.1]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[vamp-core.jar:0.7.11.1]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[vamp-core.jar:0.7.11.1]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[vamp-core.jar:0.7.11.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]

and then the GUI reports that the backend is not reachable anymore.

**Comment by zutherb** [comment]
@dragoslav here is result the info call. Is the database uploaded correct? @olafmol i will try the docker setup later. i am currently using my virtual machine installation.  
```
{

    "message": "Hi, I'm Vamp! How are you?",
    "version": "0.7.11.1",
    "jvm": 

{

    "operating_system": 

{

    "name": "Linux",
    "architecture": "amd64",
    "version": "3.16.0-30-generic",
    "available_processors": 1,
    "system_load_average": 3.44

},
"runtime": 
{

    "process": "1056@master1",
    "virtual_machine_name": "Java HotSpot(TM) 64-Bit Server VM",
    "virtual_machine_vendor": "Oracle Corporation",
    "virtual_machine_version": "25.66-b17",
    "start_time": 1445872321969,
    "up_time": 34673

},
"memory": 
{

    "heap": 

{

    "init": 12582912,
    "max": 188547072,
    "committed": 20209664,
    "used": 13297776

},
"non_heap": 

    {
        "init": 2555904,
        "max": -1,
        "committed": 61865984,
        "used": 60911248
    }

},
"threads": 

    {
        "count": 19,
        "peak_count": 19,
        "daemon_count": 5,
        "total_started_count": 20
    }

},
"persistence": 
{

    "type": "jdbc",
    "url": "jdbc:postgresql://localhost/vamp",
    "database": 

    {
        "name": "PostgreSQL",
        "version": "9.3.10",
        "schema_version": "V2 / 2015-09-08 10:28:08.558 [Up to date]"
    },
    "archive": true

},
"router": 
{

    "message": "Hi, I'm Vamp Router! How are you?",
    "version": "0.7.11",
    "status": 

    {
        "ulimit-n": "8223",
        "name": "HAProxy",
        "hard_maxconn": "4096",
        "maxconn": "4096",
        "ssl_cache_lookups": "0",
        "max_conn_rate": "0",
        "max_ssl_rate": "0",
        "run_queue": "1",
        "nbproc": "1",
        "ssl_frontend_key_rate": "0",
        "max_sess_rate": "0",
        "conn_rate": "0",
        "compress_bps_in": "0",
        "ssl_backend_max_key_rate": "0",
        "ssl_frontend_max_key_rate": "0",
        "max_zlib_mem_usage": "0",
        "curr_conns": "0",
        "sess_rate_limit": "0",
        "ssl_rate": "0",
        "zlib_mem_usage": "0",
        "conn_rate_limit": "0",
        "maxsock": "8223",
        "version": "1.5.14",
        "curr_ssl_conns": "0",
        "compress_bps_out": "0",
        "tasks": "5",
        "pid": "1165",
        "pipes_used": "0",
        "sess_rate": "0",
        "release_date": "2015/07/02",
        "cum_req": "13",
        "ssl_backend_key_rate": "0",
        "process_num": "1",
        "ssl_frontend_session_reuse_pct": "0",
        "idle_pct": "100",
        "uptime": "0d 0h00m34s",
        "cum_ssl_conns": "0",
        "memmax__mb": "0",
        "pipes_free": "0",
        "maxpipes": "0",
        "uptime_sec": "34",
        "cum_conns": "13",
        "max_ssl_conns": "0",
        "ssl_cache_misses": "0",
        "compress_bps_rate_lim": "0",
        "ssl_rate_limit": "0"
    }

},
"pulse": 
{

    "elasticsearch": 

{

    "tagline": "You Know, for Search",
    "cluster_name": "elasticsearch",
    "name": "Karolina Dean",
    "version": 

    {
        "number": "1.5.1",
        "lucene_version": "4.10.4",
        "build_snapshot": false,
        "build_timestamp": "2015-04-09T13:41:35Z",
        "build_hash": "5e38401bc4e4388537a615569ac60925788e1cf4"
    },
    "status": 200

},
"index": 
{

    "_shards": 

{

    "total": 340,
    "successful": 21,
    "failed": 0

},
"_all": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 1110152,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 1110152,
            "deleted": 0
        }
    }

},
"indices": 
{

    "vamp-pulse-event-2015-09-11": 

{

    "primaries": 

{

    "docs": 

    {
        "count": 1,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 1,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-09-14": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 4,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 4,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-10-06": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 1,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 1,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-16": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 101519,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 101519,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-10-26": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 4822,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 4822,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-10-05": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 0,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 0,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-28": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 34896,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 34896,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-06": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 55044,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 55044,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-09-12": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 1,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 1,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-10-26": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 405,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 405,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-11": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 828570,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 828570,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-29": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 5688,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 5688,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-10-05": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 66678,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 66678,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-09-10": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 3,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 3,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-09-09": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 0,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 0,
            "deleted": 0
        }
    }

},
"vamp-pulse-event-2015-10-25": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 6,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

        {
            "count": 6,
            "deleted": 0
        }
    }

},
"vamp-pulse-router-metric-2015-09-14": 
{

    "primaries": 

{

    "docs": 

    {
        "count": 12514,
        "deleted": 0
    }

},
"total": 
{

    "docs": 

                    {
                        "count": 12514,
                        "deleted": 0
                    }
                }
            }
        }
    }

},
"container_driver": 
{

    "type": "marathon",
    "container": 

{

    "name": "marathon",
    "http_config": 

{

    "assets_path": null,
    "http_port": 8080,
    "https_port": 8443

},
"framework_id": "20151025-221703-184623020-5050-1477-0000",
"leader": "master1:8080",
"event_subscriber": null,
"marathon_config": 
{

    "local_port_max": 20000,
    "local_port_min": 10000,
    "hostname": "master1",
    "master": "zk://172.31.1.11:2181/mesos",
    "reconciliation_interval": 300000,
    "leader_proxy_read_timeout_ms": 10000,
    "leader_proxy_connection_timeout_ms": 5000,
    "mesos_role": null,
    "task_launch_timeout": 300000,
    "reconciliation_initial_delay": 15000,
    "ha": true,
    "mesos_leader_ui_url": "http://172.31.1.11:5050/",
    "failover_timeout": 604800,
    "checkpoint": true,
    "webui_url": null,
    "executor": "//cmd",
    "marathon_store_timeout": 2000,
    "mesos_user": "root",
    "framework_name": "marathon"

},
"version": "0.11.1",
"zookeeper_config": 

            {
                "zk": "zk://172.31.1.11:2181/marathon",
                "zk_timeout": 10000,
                "zk_session_timeout": 1800000,
                "zk_max_versions": 25
            },
            "elected": true
        }
    }

}
```

**Comment by dragoslav** [comment]
Could you just drop that DB and restart the Vamp Core? According the info message schema is compatible even though that should not be the case (another issues).

**Comment by zutherb** [comment]
Hi @dragoslav 

your assumption was right the problem is related to the database. i can deploy the blueprint after dropping the database and now the info call looks like this

```
"persistence": {

    "type": "jdbc",
    "url": "jdbc:postgresql://localhost/vamp",
    "database": 

    {
        "name": "PostgreSQL",
        "version": "9.3.10",
        "schema_version": "V2 / 2015-10-26 08:31:08.064 [Up to date]"
    },
    "archive": true

},
```

**Comment by dragoslav** [comment]
Great! 
We plan to create an additional tool to do these updates in general (SQL schema, Elasticsearch aliases, HAProxy configuration etc.).
