### ISSUE TITLE
External gateway to specific service throws Exception

### ISSUE THREAD

**Issue by wouterd** [magneticio/vamp#520]
VAMP version: 0.8.2 (quickstart)

See https://github.com/wouterd/vamp-spike.git

After deploying the blueprint as `hello-world:1` and then PUTing the gateway, VAMP throws the following exception and the gateway doesn't go active.:

```
[ERROR] [02/01/2016 13:51:22.701] [vamp-akka.actor.default-dispatcher-113] [akka://vamp/user/gateway-driver-actor] None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$$anonfun$1.apply(HaProxyGatewayMarshaller.scala:69)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$$anonfun$1.apply(HaProxyGatewayMarshaller.scala:63)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$class.backends(HaProxyGatewayMarshaller.scala:63)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$class.convert(HaProxyGatewayMarshaller.scala:31)
	at io.vamp.gateway_driver.GatewayDriverBootstrap$$anon$1.convert(GatewayDriverBootstrap.scala:26)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$$anonfun$convert$1.apply(HaProxyGatewayMarshaller.scala:28)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$$anonfun$convert$1.apply(HaProxyGatewayMarshaller.scala:28)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$class.convert(HaProxyGatewayMarshaller.scala:28)
	at io.vamp.gateway_driver.GatewayDriverBootstrap$$anon$1.convert(GatewayDriverBootstrap.scala:26)
	at io.vamp.gateway_driver.haproxy.HaProxyGatewayMarshaller$class.marshall(HaProxyGatewayMarshaller.scala:25)
	at io.vamp.gateway_driver.GatewayDriverBootstrap$$anon$1.marshall(GatewayDriverBootstrap.scala:26)
	at io.vamp.gateway_driver.GatewayDriverActor.io$vamp$gateway_driver$GatewayDriverActor$$commit(GatewayDriverActor.scala:50)
	at io.vamp.gateway_driver.GatewayDriverActor$$anonfun$receive$1.applyOrElse(GatewayDriverActor.scala:35)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at io.vamp.gateway_driver.GatewayDriverActor.aroundReceive(GatewayDriverActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525)
	at akka.actor.ActorCell.invoke(ActorCell.scala:494)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by dragoslav** [comment]
Reproduced in 0.8.2, blueprint:
```yaml
name: sava:1.0

gateways:
  9050: sava/port

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          debug[SAVA_DEBUG]: true
    
      scale:
          cpu: 1
          memory: 64MB
          instances: 2
```
Gateway:
```yaml
name: gateway
port: 9080/http
routes:
  sava/sava/port:
    filters:
      - condition: user-agent = Firefox
  sava/9050:
    filters:
      - condition: user-agent = Chrome
```

Fixed in 0.8.3.
