### ISSUE TITLE
Missing favicon in Marathon ui pollutes the log with stack trace at INFO level

### ISSUE THREAD

**Issue by petervandenabeele** [magneticio/vamp#551]
Running the quick start on Mac OS X with Docker 1.9 show these stack traces in the log at INFO level:
```
...
[2016-02-22 21:35:27,628] INFO 192.168.99.1 - - [22/Feb/2016:21:35:27 +0000] "GET //192.168.99.100:9090/v2/apps HTTP/1.1" 200 11 "http://192.168.99.100:9090/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0" 1 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$f2c4dd1:qtp193492784-30)
[2016-02-22 21:35:27,651] INFO 192.168.99.1 - - [22/Feb/2016:21:35:27 +0000] "GET //192.168.99.100:9090/ui/img/marathon-favicon.ico HTTP/1.1" 200 32038 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0" 1 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$f2c4dd1:qtp193492784-29)
[2016-02-22 21:35:27,675] INFO 192.168.99.1 - - [22/Feb/2016:21:35:27 +0000] "GET //192.168.99.100:9090/v2/deployments HTTP/1.1" 200 2 "http://192.168.99.100:9090/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0" 6 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$f2c4dd1:qtp193492784-31)
[2016-02-22 21:35:27,687] INFO 192.168.99.1 - - [22/Feb/2016:21:35:27 +0000] "GET //192.168.99.100:9090/v2/queue HTTP/1.1" 200 12 "http://192.168.99.100:9090/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0" 6 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$f2c4dd1:qtp193492784-32)
[2016-02-22 21:35:27,739] INFO mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$98e767b8:qtp193492784-33)
com.sun.jersey.api.NotFoundException: null for uri: http://192.168.99.100:9090/favicon.ico
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1543) [marathon:0.13.0]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [marathon:0.13.0]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [marathon:0.13.0]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [marathon:0.13.0]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [marathon:0.13.0]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [marathon:0.13.0]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [marathon:0.13.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [marathon:0.13.0]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [marathon:0.13.0]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [marathon:0.13.0]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [marathon:0.13.0]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [marathon:0.13.0]
	at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18) [marathon:0.13.0]
	at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$56754fa9.CGLIB$doFilter$0(<generated>) [marathon:0.13.0]
	at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$56754fa9$$FastClassByGuice$$282e3631.invoke(<generated>) [marathon:0.13.0]
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:0.13.0]
	at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon:0.13.0]
	at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) [marathon:0.13.0]
	at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon:0.13.0]
	at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$56754fa9.doFilter(<generated>) [marathon:0.13.0]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon:0.13.0]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon:0.13.0]
	at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46) [marathon:0.13.0]
	at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$c67dab18.CGLIB$doFilter$0(<generated>) [marathon:0.13.0]
	at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$c67dab18$$FastClassByGuice$$40ee0a06.invoke(<generated>) [marathon:0.13.0]
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:0.13.0]
	at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon:0.13.0]
	at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) [marathon:0.13.0]
	at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:0.13.0]
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon:0.13.0]
	at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$c67dab18.doFilter(<generated>) [marathon:0.13.0]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon:0.13.0]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon:0.13.0]
	at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:32) [marathon:0.13.0]
	at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon:0.13.0]
	at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon:0.13.0]
	at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:36) [marathon:0.13.0]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon:0.13.0]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon:0.13.0]
	at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:126) [marathon:0.13.0]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon:0.13.0]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon:0.13.0]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [marathon:0.13.0]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [marathon:0.13.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [marathon:0.13.0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) [marathon:0.13.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:0.13.0]
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon:0.13.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:0.13.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon:0.13.0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) [marathon:0.13.0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon:0.13.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [marathon:0.13.0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon:0.13.0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon:0.13.0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon:0.13.0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon:0.13.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon:0.13.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon:0.13.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
...
```

**Comment by olafmol** [comment]
Hi @petervandenabeele tnx for reporting! Our approach is that INFO level warnings of underlying systems (like Marathon in this case) might be useful for debugging. We could issue a issue at the Marathon UI project though?

**Comment by petervandenabeele** [comment]
Well yes, printing a stack trace for a missing favicon seems a bit over the top to me ... (or just provide an empty favicon for now).

**Comment by dragoslav** [comment]
Hi @petervandenabeele `http://192.168.99.100:9090/favicon.ico` is request to Marathon (port `9090`), for instance `http://192.168.99.100:9090` gives Marathon UI. Any request to non found resource will result in stack trace - but in Marathon, not Vamp.
If you send `http://192.168.99.100:8080/favicon.ico` to Vamp (port `8080`), then just that request with headers is logged (like any other), even though `favicon.ico` is not found as well:

`
[INFO] [02/28/2016 22:05:08.099] [vamp-akka.actor.default-dispatcher-132] [akka.actor.ActorSystemImpl(vamp)] http://192.168.99.100:8080/favicon.ico - Headers: [List(Cache-Control: max-age=0, Connection: keep-alive, Cookie:...
`
It's a bit confusing just because all logs (HAProxy, Mesos/Marathon, ZooKeper, ELK and Vamp) appear in standard output, however as @olafmol said it's also valuable for quick debugging (it's a quick start anyway and there are many components).

**Comment by petervandenabeele** [comment]
Thanks for the explanation. I will close this ticket as "external issue".
