### ISSUE TITLE
Can't start vamp.

### ISSUE THREAD

**Issue by alfirin** [magneticio/vamp#635]
This is the error I got every time:
```
21:43:13.363 | ERROR | io.vamp.common.http.RestClient$          |                                          | rsp [GET http://localhost:9090/v2/apps?embed=apps.tasks] - exception: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9090 to http://localhost:9090/v2/apps?embed=apps.tasks
21:43:13.367 | ERROR | io.vamp.common.notification.Notification |                                          | Container response error.
21:43:13.371 | ERROR | io.vamp.common.notification.Notification |                                          | java.net.ConnectException: Connection refused: localhost/127.0.0.1:9090 to http://localhost:9090/v2/apps?embed=apps.tasks
io.vamp.common.http.RestClientException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9090 to http://localhost:9090/v2/apps?embed=apps.tasks
	at io.vamp.common.http.RestClient$$anonfun$http$1.applyOrElse(RestClient.scala:91) ~[vamp.jar:0.8.4]
	at io.vamp.common.http.RestClient$$anonfun$http$1.applyOrElse(RestClient.scala:80) ~[vamp.jar:0.8.4]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[vamp.jar:0.8.4]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) ~[vamp.jar:0.8.4]
	at scala.util.Try$.apply(Try.scala:192) ~[vamp.jar:0.8.4]
	at scala.util.Failure.recover(Try.scala:216) ~[vamp.jar:0.8.4]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[vamp.jar:0.8.4]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[vamp.jar:0.8.4]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [vamp.jar:0.8.4]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [vamp.jar:0.8.4]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [vamp.jar:0.8.4]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [vamp.jar:0.8.4]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [vamp.jar:0.8.4]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [vamp.jar:0.8.4]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [vamp.jar:0.8.4]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) [vamp.jar:0.8.4]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405) [vamp.jar:0.8.4]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp.jar:0.8.4]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp.jar:0.8.4]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp.jar:0.8.4]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp.jar:0.8.4]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9090 to http://localhost:9090/v2/apps?embed=apps.tasks
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[vamp.jar:0.8.4]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[vamp.jar:0.8.4]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[vamp.jar:0.8.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9090
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_66-internal]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_66-internal]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[vamp.jar:0.8.4]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[vamp.jar:0.8.4]
	... 8 common frames omitted
```

**Comment by olafmol** [comment]
Hi Jimmy, could you tell us what version of vamp you are using? And in what config? Tnx!

**Comment by dragoslav** [comment]
This looks the same as https://github.com/magneticio/vamp/issues/696, closing the issue here.
