### ISSUE TITLE
When running docker-quickstart I get this error. Eventstream does not seem to work when this appears.

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp#732]
This happens when starting vamp quikstart:

```
When runnERROR] [08/12/2016 10:13:17.831] [vamp-akka.actor.default-dispatcher-8] [akka://vamp/user/artifact-initialization-actor] null
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
	at scala.io.BufferedSource.reader(BufferedSource.scala:24)
	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:25)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader$lzycompute(BufferedSource.scala:35)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader(BufferedSource.scala:33)
	at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:62)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:91)
	at io.vamp.lifter.artifact.ArtifactInitializationActor$$anonfun$io$vamp$lifter$artifact$ArtifactInitializationActor$$loadResources$1$$anonfun$apply$3.apply(ArtifactInitializationActor.scala:69)
	at io.vamp.lifter.artifact.ArtifactInitializationActor$$anonfun$io$vamp$lifter$artifact$ArtifactInitializationActor$$loadResources$1$$anonfun$apply$3.apply(ArtifactInitializationActor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.vamp.lifter.artifact.ArtifactInitializationActor$$anonfun$io$vamp$lifter$artifact$ArtifactInitializationActor$$loadResources$1.apply(ArtifactInitializationActor.scala:64)
	at io.vamp.lifter.artifact.ArtifactInitializationActor$$anonfun$io$vamp$lifter$artifact$ArtifactInitializationActor$$loadResources$1.apply(ArtifactInitializationActor.scala:62)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at io.vamp.lifter.artifact.ArtifactInitializationActor$$anonfun$receive$1.applyOrElse(ArtifactInitializationActor.scala:43)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at io.vamp.lifter.artifact.ArtifactInitializationActor.aroundReceive(ArtifactInitializationActor.scala:26)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

After that I can't get events using a REST call. A eventstream can be opened but no events are send.

**Comment by dragoslav** [comment]
This is very strange because resources are loaded from `jar` itself, based on configuration - so configuration of quick start is something to be checked first. If resources are not loaded - `metrics`, `health` workflows then no events will be generated. Could confirm that you still get this (occasionally)?

**Comment by olafmol** [comment]
fixed
