### ISSUE TITLE
Elasticsearch url seems broken

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#754]
I'm getting a weird error in my logs on a brand new deployment on Mesos:

```
18:09:02.699 [vamp-akka.actor.default-dispatcher-5] ERROR i.v.common.notification.Notification - Persistence operation failure.
18:09:02.700 [vamp-akka.actor.default-dispatcher-5] ERROR i.v.common.notification.Notification - The URI scheme, of the URI ///vamp-persistence/deployments/_search, must be equal (ignoring case) to 'http', 'https', 'ws', or 'wss'
java.lang.IllegalArgumentException: The URI scheme, of the URI ///vamp-persistence/deployments/_search, must be equal (ignoring case) to 'http', 'https', 'ws', or 'wss'
	at com.ning.http.util.AsyncHttpProviderUtils.validateSupportedScheme(AsyncHttpProviderUtils.java:55) ~[vamp.jar:0.9.0]
	at com.ning.http.client.RequestBuilderBase$RequestImpl.toURI(RequestBuilderBase.java:175) ~[vamp.jar:0.9.0]
	at com.ning.http.client.RequestBuilderBase$RequestImpl.getURI(RequestBuilderBase.java:158) ~[vamp.jar:0.9.0]
	at com.ning.http.client.RequestBuilderBase$RequestImpl.getUrl(RequestBuilderBase.java:144) ~[vamp.jar:0.9.0]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:990) ~[vamp.jar:0.9.0]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:935) ~[vamp.jar:0.9.0]
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499) ~[vamp.jar:0.9.0]
	at dispatch.HttpExecutor$class.apply(execution.scala:47) ~[vamp.jar:0.9.0]
	at dispatch.Http.apply(execution.scala:12) ~[vamp.jar:0.9.0]
	at dispatch.HttpExecutor$class.apply(execution.scala:42) ~[vamp.jar:0.9.0]
	at dispatch.Http.apply(execution.scala:12) ~[vamp.jar:0.9.0]
	at io.vamp.common.http.RestClient$.http(RestClient.scala:64) ~[vamp.jar:0.9.0]
	at io.vamp.common.http.RestClient$.post(RestClient.scala:38) ~[vamp.jar:0.9.0]
	at io.vamp.pulse.ElasticsearchClient.search(ElasticsearchClient.scala:86) ~[vamp.jar:0.9.0]
	at io.vamp.persistence.db.ElasticsearchPersistenceActor.all(ElasticsearchPersistenceActor.scala:41) [vamp.jar:0.9.0]
	at io.vamp.persistence.db.PersistenceActor$$anonfun$receive$1$$anonfun$applyOrElse$3.apply(PersistenceActor.scala:71) ~[vamp.jar:0.9.0]
	at io.vamp.persistence.db.PersistenceActor$$anonfun$receive$1$$anonfun$applyOrElse$3.apply(PersistenceActor.scala:71) ~[vamp.jar:0.9.0]
	at scala.util.Try$.apply(Try.scala:192) ~[vamp.jar:0.9.0]
	at io.vamp.common.akka.ReplyMagnet$$anon$1.get(ReplyActor.scala:57) ~[vamp.jar:0.9.0]
	at io.vamp.common.akka.ReplyActor$class.reply(ReplyActor.scala:22) [vamp.jar:0.9.0]
	at io.vamp.persistence.db.ElasticsearchPersistenceActor.reply(ElasticsearchPersistenceActor.scala:25) [vamp.jar:0.9.0]
	at io.vamp.persistence.db.PersistenceActor$$anonfun$receive$1.applyOrElse(PersistenceActor.scala:70) [vamp.jar:0.9.0]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [vamp.jar:0.9.0]
	at io.vamp.persistence.db.ElasticsearchPersistenceActor.aroundReceive(ElasticsearchPersistenceActor.scala:25) [vamp.jar:0.9.0]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [vamp.jar:0.9.0]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [vamp.jar:0.9.0]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [vamp.jar:0.9.0]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [vamp.jar:0.9.0]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [vamp.jar:0.9.0]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp.jar:0.9.0]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp.jar:0.9.0]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp.jar:0.9.0]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp.jar:0.9.0]
18:09:02.702 [vamp-akka.actor.default-dispatcher-2] DEBUG c.n.h.c.p.n.NettyAsyncHttpProvider - Using cached Channel [id: 0xf170e7aa, /172.17.0.11:55208 => efk.service.consul/10.200.26.107:9200]
 for uri http://efk.service.consul:9200/vamp-pulse-event-2016-09-14/event

18:09:02.703 [vamp-akka.actor.default-dispatcher-2] DEBUG c.n.h.c.p.n.NettyAsyncHttpProvider - 
Using cached Channel [id: 0xf170e7aa, /172.17.0.11:55208 => efk.service.consul/10.200.26.107:9200]
 for request 
DefaultHttpRequest(chunked: false)
POST /vamp-pulse-event-2016-09-14/event HTTP/1.1
Host: efk.service.consul:9200
Accept: application/json
Content-Type: application/json
Connection: keep-alive
User-Agent: Dispatch/0.11.1-SNAPSHOT
Content-Length: 175
```

The web GUI is showing up just fine, but hitting the INFO button all items are blank. The eventviewer in the bottom is flooding me with:

```
20:23:40 	info   persistence   persistence:ERROR   	IllegalArgumentException
```

Looking at Elastic, there _is_ an index named *vamp-pulse-event-2016-09-14*.

Here is the json I used to deploy vamp:
```
{
    "id": "vamp/vamp",
    "instances": 1,
    "cpus": 0.5,
    "mem": 1024,
    "labels": {"team":"purple"},
    "cmd": "
        java 
        -Dlogback.configurationFile=/usr/local/vamp/conf/logback.xml 
        -Dvamp.gateway-driver.haproxy.ip=172.17.42.1
        -Dvamp.gateway-driver.haproxy.virtual-hosts.ip=172.17.42.1
        -Dvamp.gateway-driver.haproxy.virtual-hosts.port=2002
        -Dvamp.gateway-driver.virtual-hosts=true
        -Dvamp.operation.gateway.virtual-hosts.formats.gateway=$gateway.blaze
        -Dvamp.persistence.key-value-store.consul.url=http://consul.blaze:8500
        -Dvamp.persistence.key-value-store.type=consul
        -Dvamp.pulse.elasticsearch.url=http://efk.service.consul:9200
        -jar /usr/local/vamp/vamp.jar",
    "container": {
        "type": "DOCKER",
        "docker": {
            "portMappings": [{
                "hostPort": 0,
                "containerPort": 5000,
                "protocol": "tcp"
            }],
            "image": "magneticio/vamp:0.9.0",
            "network": "BRIDGE",
            "forcePullImage": true,
            "parameters": [{
                "key": "dns",
                "value": "172.17.42.1"
            }]
        }
    },
    "env": {
        "VAMP_REST_API_PORT": "5000",
        "VAMP_CONTAINER_DRIVER_MESOS_URL": "http://mesos-master.service.consul:5050",
        "VAMP_CONTAINER_DRIVER_MARATHON_URL": "http://mesos-master.service.consul:8080",
        "VAMP_CONTAINER_DRIVER_TYPE": "marathon",
        "VAMP_PULSE_ELASTICSEARCH_URL": "http://efk.service.consul:9200",
        "VAMP_LIFTER_VAMP_GATEWAY_AGENT_ENABLED": "false",
        "SERVICE_5000_TAGS": "infrastructure,team-purple"
    }
}
```

Am I missing something here, since this used to work on 0.8?

**Comment by dragoslav** [comment]
There are small changes in configuration, change `env`:
- remove `VAMP_LIFTER_VAMP_GATEWAY_AGENT_ENABLED` (will be ignored anyway)
- add `"VAMP_LIFTER_ARTIFACT_FILES": "[\"breeds/health.js\",\"workflows/health.yml\",\"breeds/metrics.js\",\"workflows/metrics.yml\",\"breeds/kibana.js\",\"workflows/kibana.yml\"]"` for default metrics/health workflows (otherwise `"VAMP_LIFTER_ARTIFACT_FILES": "[]"`)
- add `"VAMP_DATABASE_ELASTICSEARCH_URL": "http://efk.service.consul:9200"` this one was causing the error
- set `"VAMP_WORKFLOW_DRIVER_VAMP_URL"` if you want to have default workflows enabled (or run them later)

**Comment by harmw** [comment]
Ah, excellent, will give this a try 👍 (it's stuff like this I would've liked to see in a changelog/release-notes, but fair enough)

What would be the difference between the _database_ url and the _pulse_ url? (regarding Elasticsearch)

Any value I should set for *VAMP_WORKFLOW_DRIVER_VAMP_URL*? Eg. what is expected to be listening on the other end there?

**Comment by olafmol** [comment]
@harmw you're of course right about this, thanks for pointing this out. Will make a better effort to describe these changes in the release notes. Tnx!

**Comment by harmw** [comment]
Crap, still seeing the error. _/api/v1/info_ shows me this:
```
  "persistence": {
    "error": "No response."
  },
```

Furthermore:
```
19:03:03.234 [vamp-akka.actor.default-dispatcher-14] ERROR i.v.common.notification.Notification - The URI scheme, of the URI ///vamp-persistence/blueprints/_search, must be equal (ignoring case) to 'http', 'https', 'ws', or 'wss'
```
And:
```
[ERROR] [09/14/2016 19:03:03.249] [vamp-akka.actor.default-dispatcher-14] [akka://vamp/user/http-server-actor] Request to http://vamp.trusted.play.ground.dev.blaze.ps/api/v1/blueprints could not be handled normally: Ask timed out on [Actor[akka://vamp/user/elasticsearch-persistence-actor#-1528064055]] after [10000 ms]. Sender[null] sent message of type "io.vamp.persistence.db.PersistenceActor$All".
```

**Comment by dragoslav** [comment]
`VAMP_WORKFLOW_DRIVER_VAMP_URL` => `marathon` if you have Chronos running you can add it as well `marathon,chronos`
We use Elasticsearch for:
- persistence
- events (pulse)
In 0.9.1 we are adding support for K/V store persistence https://github.com/magneticio/vamp/issues/750, so you could use Consul for resource (artifact) persistence and Elasticsearch for events

You can use `/api/v1/config` to inspect your configuration - every entry can be overriden by an environment variable.

I was wrong, typo, should be `"VAMP_PERSISTENCE_DATABASE_ELASTICSEARCH_URL"` not `""VAMP_DATABASE_ELASTICSEARCH_URL"` (definitely need to have a changelog).

**Comment by harmw** [comment]
Ok, giving it another shot 👍 
*VAMP_WORKFLOW_DRIVER_VAMP_URL* looks like it expects a url (http://[...]) but definately not a string `marathon` 😅

**Comment by harmw** [comment]
victory! thanks @dragoslav

**Comment by dragoslav** [comment]
Yes, it's getting late :) For some reason I was talking about workflow driver types.
Anyway, it should be the Vamp URL - so workflows could access to Vamp API.

**Comment by harmw** [comment]
ah ok, will change that - thanks!
