### ISSUE TITLE
Vamp unable to connect to Rancher API when on different host

### ISSUE THREAD

**Issue by stefanvangastel** [magneticio/vamp#800]
The **Running Vamp** section on http://vamp.io/documentation/installation/rancher/ instructs you to get the **local** aka same-host ip-address of the Rancher server (172.17.0.x). 

This implies the Vamp service is running on the same host as the Rancher server container. If you have a multi host Rancher setup (e.g. 1 VM with only Rancher server and 10 VM's acting as Rancher hosts/agents) this will not work since every host has his own 172.17.0.x network. 

Thus we should be able to provide the full Rancher API URL (e.g. http://rancher.example.com:8080/v1/projects/1a5) as the [Rancher API button](http://docs.rancher.com/rancher/v1.2/en/api/) returns, even more, it should be possible to provide token authentication for the Rancher API.

I am experiencing this issue when [deploying Vamp from catalog](https://github.com/rancher/community-catalog/pull/307)  in an offline environment. 

- Rancher server 1.1.4
- Rancher Access Control: Active Directory
- Created an [Environment API Key](http://docs.rancher.com/rancher/v1.2/en/api/api-keys/#adding-environment-api-keys)
- Launched Vamp container through Rancher with `VAMP_CONTAINER_DRIVER_RANCHER_URL` set to:
  - `http://rancher.example.com:8080/v1/projects/1a5`
    - cURL from within Vamp container `# curl $VAMP_CONTAINER_DRIVER_RANCHER_URL`: Rancher API unauthorized error
    - Logging from within Vamp container: Rancher API unauthorized error
  - `http://<api_access_key>:<api_secret>@rancher.example.com:8080/v1/projects/1a5`
    - cURL from within Vamp container `# curl $VAMP_CONTAINER_DRIVER_RANCHER_URL`: Rancher API responding as intended
    - Logging from within Vamp container: Rancher API unauthorized error

Anyone able to find the issue? It seems like the Vamp REST client is either ignoring or stripping away the auth data in the URL. 

Best solution would be to be able to provide a VAMP_CONTAINER_DRIVER_RANCHER_API_KEY and VAMP_CONTAINER_DRIVER_RANCHER_API_SECRET.

A piece of the logfile included. Again, using cURL (from anywhere and within Vamp container) on unmodified version of URL in the logfile works. 

[vamp_error_log.txt](https://github.com/magneticio/vamp/files/541864/vamp_error_log.txt)

**Comment by stefanvangastel** [comment]
The logfile: 
```
[36m13:51:35.259[0;39m [1;31m| ERROR | io.vamp.common.http.RestClient$          |                                          | rsp [GET http://A904BD:fbvqb2UAyYGQXzZ@rancher.example.com:8080/v1/projects/1a7/services?name=vamp-workflow-kibana] - unexpected status code: 401
20-10-2016 15:51:35[0;39m[36m13:51:35.259[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Container response error.
20-10-2016 15:51:35[0;39m[36m13:51:35.262[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | {"id":"92b9e7b7-03a7-4990-b5f5-ebc13140ebbe","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
20-10-2016 15:51:35[0;39mio.vamp.common.http.RestClientException: {"id":"92b9e7b7-03a7-4990-b5f5-ebc13140ebbe","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
20-10-2016 15:51:35    at io.vamp.common.http.RestClient$$anon$1.onCompleted(RestClient.scala:80) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:293) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:320) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1533) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1550) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2700(NettyAsyncHttpProvider.java:161) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2220) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1228) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp.jar:0.9.0]
20-10-2016 15:51:35    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[vamp.jar:0.9.0]
```

**Comment by stefanvangastel** [comment]
Based on some searching, the best-case scenario is that its an undocumented feature:
https://github.com/magneticio/vamp/blob/f0be97a945f62b9b2e900ded03b493d486212249/container_driver/src/main/scala/io/vamp/container_driver/rancher/RancherDriverActor.scala#L25

**Comment by stefanvangastel** [comment]
To conclude this monologue :)

Undocumented features fixed the issue: https://github.com/magneticio/vamp.io/pull/22
