### ISSUE TITLE
Workflow creation fails with katana build on kubernetes

### ISSUE THREAD

**Issue by vlesierse** [magneticio/vamp#852]
I've tried a recent build of Vamp which should include the rollback of the HTTP client because the other one had problems using HTTPS. Unfortunately I still get errors when Vamp tries to create workflow containers in Kubernetes.

Versions:
Vamp: 0.9.1-31-gd0a1cb7
Kubernetes: 1.4.3

```
2016-12-12T14:54:48.864631114Z 14:54:48.864 | ERROR | io.vamp.common.http.HttpClient | | rsp [HttpMethod(POST) https://kubernetes/apis/extensions/v1beta1/namespaces/default/deployments] - exception: Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.865766171Z 14:54:48.865 | ERROR | io.vamp.common.notification.Notification | | Container response error.
2016-12-12T14:54:48.865978091Z 14:54:48.865 | ERROR | io.vamp.common.notification.Notification | | Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.865993684Z io.vamp.common.http.HttpClientException: Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.865997245Z at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:127)
2016-12-12T14:54:48.865999833Z at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:116)
2016-12-12T14:54:48.866003818Z at akka.stream.impl.fusing.Recover$$anon$11.onUpstreamFailure(Ops.scala:255)
2016-12-12T14:54:48.866006224Z at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733)
2016-12-12T14:54:48.866014549Z at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
2016-12-12T14:54:48.866017246Z at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
2016-12-12T14:54:48.866019707Z at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:429)
2016-12-12T14:54:48.866022494Z at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
2016-12-12T14:54:48.866025081Z at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
2016-12-12T14:54:48.866027767Z at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
2016-12-12T14:54:48.866030291Z at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
2016-12-12T14:54:48.866032700Z at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
2016-12-12T14:54:48.866035027Z at akka.actor.ActorCell.invoke(ActorCell.scala:495)
2016-12-12T14:54:48.866037391Z at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
2016-12-12T14:54:48.866039702Z at akka.dispatch.Mailbox.run(Mailbox.scala:224)
2016-12-12T14:54:48.866042003Z at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
2016-12-12T14:54:48.866044370Z at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2016-12-12T14:54:48.866046717Z at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
2016-12-12T14:54:48.866049134Z at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
2016-12-12T14:54:48.866051504Z at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-12-12T14:54:48.866054786Z Caused by: akka.stream.StreamTcpException: Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.866174733Z [ERROR] [12/12/2016 14:54:48.865] [vamp-akka.actor.default-dispatcher-10] [akka://vamp/user/StreamSupervisor-9/flow-1145-0-unknown-operation] Error in stage [Recover(<function1>)]: Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.866187734Z io.vamp.common.http.HttpClientException: Tcp command [Connect(kubernetes:0,None,List(),Some(10 seconds),true)] failed
2016-12-12T14:54:48.866192044Z at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:127)
2016-12-12T14:54:48.866194793Z at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:116)
2016-12-12T14:54:48.866197431Z at akka.stream.impl.fusing.Recover$$anon$11.onUpstreamFailure(Ops.scala:255)
2016-12-12T14:54:48.866199976Z at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733)
2016-12-12T14:54:48.866202404Z at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
2016-12-12T14:54:48.866204906Z at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
```

**Comment by olafmol** [comment]
@iamtew could you take a look and see if this might because of some configuration setting where the port needs to be specified?

**Comment by dragoslav** [comment]
it seems as https://github.com/magneticio/vamp/issues/859 - port is not specified anyway.

**Comment by vlesierse** [comment]
Ok, I will build a new katana and see if it works. Keep you posted

**Comment by vlesierse** [comment]
Yep, its work now. Last hurdle is the gateway agent which remains in an error stand and doesn't show any output... I will create a issue in that repo.

**Comment by dragoslav** [comment]
Closing it because Vamp `katana` seems to work fine, otherwise we can create a new issue. One way to test it including with `minikube` is: 
```bash
curl -s https://raw.githubusercontent.com/magneticio/vamp-docker/master/vamp-kubernetes/vamp_kube_quickstart.sh | bash -s -- -k
```
