### ISSUE TITLE
Workflows giving CrashLoopBackOff on Kubernetes

### ISSUE THREAD

**Issue by thecodeassassin** [magneticio/vamp#865]
Happens when using the latest katana release of Vamp.

Image ID: magneticio/vamp  katana-kubernetes   9d9f65ed135f

```
$ kubectl logs vamp-workflow-metrics-3704047774-16pur
08:39:37.886 main NOTI ==>
██╗   ██╗ █████╗ ███╗   ███╗██████╗
██║   ██║██╔══██╗████╗ ████║██╔══██╗
██║   ██║███████║██╔████╔██║██████╔╝
╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       workflow agent
                       version katana
                       by magnetic.io

08:39:37.886 main CRIT ==> Execution period must be specified and it must be equal or greater than 0.
panic: Execution period must be specified and it must be equal or greater than 0.

goroutine 1 [running]:
panic(0x8cf080, 0xc42011cc70)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/op/go-logging.(*Logger).Panic(0xc42011ac00, 0xc420035d90, 0x1, 0x1)
	/Users/dragoslav/workspace/go/src/github.com/op/go-logging/logger.go:182 +0x160
main.checkInt(0xc42011c9e0, 0x9cb768, 0x18, 0x9d880c, 0x4a)
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:111 +0x1d1
main.main()
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:57 +0x15b
```

Also i see local paths in the stack trace, should this be there?

**Comment by dragoslav** [comment]
This is in general "problem" with `katana` snapshots - there was an incompatibility between Vamp components - changing 1 component but not applying yet that change to others. Yes, local path should not be there - I just built the Docker image locally and pushed it to repo - starting from the next release only officially built images will be allowed (built by dedicated build server).

**Comment by olafmol** [comment]
solved
