### ISSUE TITLE
when changing scale in marathon sometimes error is shown in Vamp events

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#892]
21:52:32.201 	event 	marathon_driver:ERROR info 	HttpClientException

**Comment by dragoslav** [comment]
Could you enable trace log and post the actual response from the server? It is possible to get timeouts or rejects due to too frequent change.

**Comment by olafmol** [comment]
```
20:52:32.096 | INFO  | i.v.c.marathon.MarathonDriverActor       | kka://vamp/user/marathon-driver-actor-25 | marathon update service: sava / magneticio/sava:1.0.0
20:52:32.184 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(PUT) http://localhost:9090/v2/apps//sava/sava-1-0-0-6fd83b1fd01f7dd9eb7f] - unexpected status code: 409
20:52:32.201 | WARN  | io.vamp.common.notification.Notification |                                          | No mapping for class io.vamp.container_driver.notification.ContainerResponseError
20:52:32.204 | ERROR | io.vamp.common.notification.Notification |                                          | Notification.
20:52:32.209 | ERROR | io.vamp.common.notification.Notification |                                          | {"message":"App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'.","deployments":[{"id":"12c8f38f-fa0b-4727-8fcd-092f449a7ffb"}]}
io.vamp.common.http.HttpClientException: {"message":"App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'.","deployments":[{"id":"12c8f38f-fa0b-4727-8fcd-092f449a7ffb"}]}
	at io.vamp.common.http.HttpClient.$anonfun$httpWithEntity$9(HttpClient.scala:158)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
20:52:35.100 | INFO  | i.v.c.marathon.MarathonDriverActor       | kka://vamp/user/marathon-driver-actor-25 | marathon update service: sava / magneticio/sava:1.0.0
20:52:38.047 | ERROR | io.vamp.common.notification.Notification |                                          | Deployment service error for deployment 'sava' and service 'sava:1.0.0'.
```

**Comment by olafmol** [comment]
I did the scaling in the Marathon UI and indeed frequently, to validate if/how Vamp would correct this.

**Comment by dragoslav** [comment]
In case of possible `force=true` use (might be configurable), I would rather by default back off for a while, like using https://github.com/magneticio/vamp/issues/705

**Comment by olafmol** [comment]
closing this as we will implement #705 at some point to handle component failure more gracefully to avoid overloading.
