### ISSUE TITLE
[093] Event based workflows throw error 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#917]
running 093 docker quickstart on mac os X. When creating a test workflow that creates custom event:

```
name: hello_workflow
kind: breed
metadata: {}
deployable:
  type: application/javascript
  definition: |
    'use strict';

    var vamp = require('vamp-node-client'); // required to interact with the Vamp API

    var api = new vamp.Api(); // a new Vamp API object

    // create a Vamp event - tag, value, event_type
    api.event('olaf:test', '1234', 'hello_workflow');
ports: {}
environment_variables: {}
constants: {}
arguments: []
dependencies: {}
```

and then create another workflow that is reacting on this event:

```
name: hello_workflow_event
kind: workflow
metadata: {}
breed:
  reference: hello_workflow_event
status: running
schedule:
  event:
    tags:
    - olaf:test
environment_variables:
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: '2'
  VAMP_KEY_VALUE_STORE_CONNECTION: 192.168.99.100:2181
  VAMP_KEY_VALUE_STORE_PATH: /vamp/workflows/hello_workflow_event
  VAMP_WORKFLOW_EXECUTION_PERIOD: '3'
  VAMP_ELASTICSEARCH_URL: http://localhost:9200
  VAMP_KEY_VALUE_STORE_TYPE: zookeeper
  VAMP_URL: http://192.168.99.100:8080
scale:
  cpu: 0.1
  memory: 128.00MB
  instances: 1
network: HOST
arguments:
- privileged: 'true'
instances:
- name: hello_workflow_event
  host: ''
  ports: {}
  deployed: true
  metadata: {}
```

there is an error the moment the event is detected and the workflow tries to react. In the event stream:

```
14:20:45.682	event	workflow_driver:ERROR info	ClassCastException
14:20:45.657	event	chronos_workflow:ERROR info	ClassCastException
14:20:45.646	hello_workflow	olaf:test	1234
14:20:43.685	event	workflow_driver:ERROR info	ClassCastException
14:20:43.661	event	chronos_workflow:ERROR info	ClassCastException
```

and in the Vamp log:

```
13:15:43.646 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/workflow-actor-18       | Triggering workflow: 'hello_workflow_event'.
13:15:43.668 | ERROR | io.vamp.common.notification.Notification |                                          | Generic error.
13:15:43.698 | ERROR | io.vamp.common.notification.Notification |                                          | io.vamp.model.artifact.BreedReference cannot be cast to io.vamp.model.artifact.DefaultBreed
java.lang.ClassCastException: io.vamp.model.artifact.BreedReference cannot be cast to io.vamp.model.artifact.DefaultBreed
	at io.vamp.workflow_driver.ChronosWorkflowActor$$anonfun$schedule$1.$anonfun$applyOrElse$1(ChronosWorkflowActor.scala:77)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
13:15:43.698 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:15:43.698 | ERROR | io.vamp.common.notification.Notification |                                          | io.vamp.model.artifact.BreedReference cannot be cast to io.vamp.model.artifact.DefaultBreed
java.lang.ClassCastException: io.vamp.model.artifact.BreedReference cannot be cast to io.vamp.model.artifact.DefaultBreed
	at io.vamp.workflow_driver.ChronosWorkflowActor$$anonfun$schedule$1.$anonfun$applyOrElse$1(ChronosWorkflowActor.scala:77)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by dragoslav** [comment]
It works fine in the latest `katana` (after 0.9.3 there was already a change that could cover this).
